#!/usr/bin/perl

use strict;

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


my ($first, $second) = (1, 2);
my (@sequence) = ($first,$second);
my (@even, $sum);


while(($first + $second) < 4000000){
	
	$sum = $first + $second;
	
	push @sequence, ($sum);
	
	$first = $second;
	$second = $sum;
	
	
}


$sum = 0;

$sum += $_ foreach grep{!($_ % 2)} @sequence;

print $sum;

